
package VentanasGUI;

import Model.Controladora;
import Model.FuncionarioGeneral;
import Model.Medico;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class CantPacientesAtendidosPorMedico extends javax.swing.JFrame {
    public Controladora controlPA;
    /**
     * Creates new form CantPacientesAtendidos
     * @param control es la controladora que se pasa entre ventanas
     */
    public CantPacientesAtendidosPorMedico(Controladora control) {
        initComponents();
        this.controlPA = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        txtTitle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JLabel();
        txtFecha2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtCargaId = new javax.swing.JTextField();
        txtAdvertencia3 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        txtAdvertencia = new javax.swing.JLabel();
        txtAdvertencia2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlbCargar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbVolver = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(688, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 0, 0));
        txtTitle.setText("Cantidad de pacientes");
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        txtTitle2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        txtTitle2.setForeground(new java.awt.Color(0, 0, 0));
        txtTitle2.setText("atendidos por médico");
        jPanel1.add(txtTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        tablaMedicos.setBackground(new java.awt.Color(255, 255, 255));
        tablaMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaMedicos.setForeground(new java.awt.Color(0, 0, 0));
        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMedicos.setShowGrid(true);
        jScrollPane1.setViewportView(tablaMedicos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 510, 130));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tabla de médicos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        txtFecha1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        txtFecha1.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha1.setText("Primer Fecha:");
        jPanel1.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        txtFecha2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        txtFecha2.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha2.setText("Segunda Fecha:");
        jPanel1.add(txtFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 150, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 150, -1));

        txtCargaId.setBackground(new java.awt.Color(255, 255, 255));
        txtCargaId.setForeground(new java.awt.Color(0, 0, 0));
        txtCargaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtCargaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 150, -1));

        txtAdvertencia3.setBackground(new java.awt.Color(255, 0, 0));
        txtAdvertencia3.setForeground(new java.awt.Color(0, 0, 0));
        txtAdvertencia3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtAdvertencia3.setOpaque(true);
        jPanel1.add(txtAdvertencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 194, 51));

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtResultado.setOpaque(true);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 112, 36));

        txtAdvertencia.setBackground(new java.awt.Color(255, 255, 255));
        txtAdvertencia.setForeground(new java.awt.Color(255, 51, 51));
        txtAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdvertencia.setText("Ingrese solo numeros enteros");
        txtAdvertencia.setOpaque(true);
        jPanel1.add(txtAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 163, 28));

        txtAdvertencia2.setBackground(new java.awt.Color(255, 255, 255));
        txtAdvertencia2.setForeground(new java.awt.Color(255, 0, 0));
        txtAdvertencia2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdvertencia2.setText("Ingresar Id");
        txtAdvertencia2.setOpaque(true);
        jPanel1.add(txtAdvertencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 163, 28));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Resultado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 36));

        jPanel3.setBackground(new java.awt.Color(149, 210, 255));

        jlbCargar.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        jlbCargar.setForeground(new java.awt.Color(0, 0, 0));
        jlbCargar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCargar.setText("Cargar Datos");
        jlbCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCargarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCargarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cruz.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(149, 210, 255));

        jlbVolver.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        jlbVolver.setForeground(new java.awt.Color(0, 0, 0));
        jlbVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbVolver.setText("Volver");
        jlbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 110, 30));

        jLabel4.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otro.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(694, 520));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtCargaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaIdActionPerformed

    /**
     * Carga una tabla con los medicos y prepara advertencias para los campos
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtAdvertencia.setVisible(false);
        txtAdvertencia2.setVisible(false);
        txtAdvertencia3.setVisible(false);
        this.cargarMedicos();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jlbCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCargarMouseClicked
        boolean estado = false;
        Calendar fechaOne = jDateChooser1.getCalendar();
        Calendar fechaTwo = jDateChooser2.getCalendar();
        
        int diaOne = fechaOne.get(Calendar.DATE);
        int mesOne = fechaOne.get(Calendar.MONTH) + 1;
        int anioOne = fechaOne.get(Calendar.YEAR);
        
        int diaTwo = fechaTwo.get(Calendar.DATE);
        int mesTwo = fechaTwo.get(Calendar.MONTH) + 1;
        int anioTwo = fechaTwo.get(Calendar.YEAR);
        
        LocalDate fecha1= LocalDate.of(anioOne,mesOne,diaOne);
        LocalDate fecha2= LocalDate.of(anioTwo,mesTwo,diaTwo);
        Integer pruebaId;
        try {
            pruebaId = Integer.valueOf(this.txtCargaId.getText());
            
            if ((pruebaId != null) && (pruebaId > 0)) {
                estado = true;
            }
            else {
                txtAdvertencia2.setVisible(true);
            }
        }
        catch (Exception e){
            txtAdvertencia.setVisible(true);
            estado = false;
        }
        try {
//            long parseId = pruebaId.longValue();
//            if (estado) {
//                String resultado = controlPA.pacientesPorMedico(fecha1, fecha2, parseId);
//                txtResultado.setText(resultado);
//            }
        }
        catch (Exception e) {
            txtAdvertencia3.setText("FatalError \n No se pudo completar la peticion \n Comuniquese con el area de Sistemas");
            txtAdvertencia.setVisible(true);
        }
    }//GEN-LAST:event_jlbCargarMouseClicked

    private void jlbCargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCargarMouseEntered
        jlbCargar.setForeground(Color.white);
    }//GEN-LAST:event_jlbCargarMouseEntered

    private void jlbCargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCargarMouseExited
        jlbCargar.setForeground(Color.black);
    }//GEN-LAST:event_jlbCargarMouseExited

    private void jlbVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseClicked
        Gestor pantallaGestor = new Gestor(controlPA);
        pantallaGestor.setVisible(true);
        pantallaGestor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbVolverMouseClicked

    private void jlbVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseEntered
        jlbVolver.setForeground(Color.white);
    }//GEN-LAST:event_jlbVolverMouseEntered

    private void jlbVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseExited
        jlbVolver.setForeground(Color.black);
    }//GEN-LAST:event_jlbVolverMouseExited
    
    /**
     * Contiene la logica para que la GUI muestre los datos de los medicos
     */
    private void cargarMedicos(){
      
        DefaultTableModel modeloTabla = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
       
        String titulos[] = {"Nombre", "Apellido", "Numero Matricula", "Id"};
        modeloTabla.setColumnIdentifiers(titulos);

        List<Medico> listaMedicos = controlPA.traerMedicos();

        if (listaMedicos != null) {

            for (Medico medicoAux : listaMedicos) {
                
                Object[] objeto = {medicoAux.getNombre(), medicoAux.getApellido(), medicoAux.getNumMat(), medicoAux.getId()};

                modeloTabla.addRow(objeto);
            }
        }
        tablaMedicos.setModel(modeloTabla);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCargar;
    private javax.swing.JLabel jlbVolver;
    private javax.swing.JTable tablaMedicos;
    private javax.swing.JLabel txtAdvertencia;
    private javax.swing.JLabel txtAdvertencia2;
    private javax.swing.JLabel txtAdvertencia3;
    private javax.swing.JTextField txtCargaId;
    private javax.swing.JLabel txtFecha1;
    private javax.swing.JLabel txtFecha2;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle2;
    // End of variables declaration//GEN-END:variables
}
