/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasGUI;

import Model.Controladora;
import Model.Paciente;
import java.awt.Color;

/**
 *
 * @author yairc
 */
public class DatosDePaciente extends javax.swing.JFrame {

    Controladora control;
    Paciente paciente;

    /**
     * Creates new form DatosDePaciente
     *
     * @param control
     * @param paciente
     */
    public DatosDePaciente(Controladora control, Paciente paciente) {
        initComponents();
        this.control = control;
        this.paciente = paciente;
        this.datosPActual.setText(paciente.getNombre()+" "+paciente.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlbVerResEstudios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbVerDiagClinico = new javax.swing.JLabel();
        jlbVerConsuAnteriores = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlbVolver = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        datosPActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Datos de paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(149, 210, 255));

        jPanel4.setBackground(new java.awt.Color(149, 210, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbVerResEstudios.setBackground(new java.awt.Color(255, 255, 255));
        jlbVerResEstudios.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlbVerResEstudios.setForeground(new java.awt.Color(0, 0, 0));
        jlbVerResEstudios.setText("Ver Resultados de Estudios");
        jlbVerResEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbVerResEstudiosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbVerResEstudiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbVerResEstudiosMouseExited(evt);
            }
        });
        jPanel4.add(jlbVerResEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 53, -1, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 238, 60, 10));

        jlbVerDiagClinico.setBackground(new java.awt.Color(255, 255, 255));
        jlbVerDiagClinico.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlbVerDiagClinico.setForeground(new java.awt.Color(0, 0, 0));
        jlbVerDiagClinico.setText("Ver Diagnosticos Clinicos");
        jlbVerDiagClinico.setMaximumSize(new java.awt.Dimension(242, 23));
        jlbVerDiagClinico.setMinimumSize(new java.awt.Dimension(242, 23));
        jlbVerDiagClinico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbVerDiagClinicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbVerDiagClinicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbVerDiagClinicoMouseExited(evt);
            }
        });
        jPanel4.add(jlbVerDiagClinico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 103, 240, 30));

        jlbVerConsuAnteriores.setBackground(new java.awt.Color(255, 255, 255));
        jlbVerConsuAnteriores.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlbVerConsuAnteriores.setForeground(new java.awt.Color(0, 0, 0));
        jlbVerConsuAnteriores.setText("Ver Consultas Anteriores");
        jlbVerConsuAnteriores.setMaximumSize(new java.awt.Dimension(242, 23));
        jlbVerConsuAnteriores.setMinimumSize(new java.awt.Dimension(242, 23));
        jlbVerConsuAnteriores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbVerConsuAnterioresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbVerConsuAnterioresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbVerConsuAnterioresMouseExited(evt);
            }
        });
        jPanel4.add(jlbVerConsuAnteriores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 240, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, 10));

        jlbVolver.setBackground(new java.awt.Color(255, 255, 255));
        jlbVolver.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlbVolver.setForeground(new java.awt.Color(0, 0, 0));
        jlbVolver.setText("Volver");
        jlbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbVolverMouseExited(evt);
            }
        });
        jPanel4.add(jlbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 203, 60, 30));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 240, 10));

        datosPActual.setBackground(new java.awt.Color(153, 204, 255));
        datosPActual.setOpaque(true);
        jPanel4.add(datosPActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 240, 31));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 270, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que se ejecuta cuando se hace clic en el componente
     * 'jlbVerResEstudios'. Este método abre la ventana para ver los resultados
     * de los estudios y cierra la ventana actual.
     *
     * @param evt El evento.
     */
    private void jlbVerResEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerResEstudiosMouseClicked
        VerResultadoEstudio verResEstu = new VerResultadoEstudio(control, paciente);
        verResEstu.setVisible(true);
        verResEstu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbVerResEstudiosMouseClicked
    /**
     * Método que se ejecuta cuando se hace clic en el componente
     * 'jlbVerConsuAnteriores'. Este método abre la ventana para ver las
     * consultas anteriores y cierra la ventana actual.
     *
     * @param evt El evento.
     */
    private void jlbVerDiagClinicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerDiagClinicoMouseClicked
        VerDiagnosticoClinico verAntCli = new VerDiagnosticoClinico(control, paciente);
        verAntCli.setVisible(true);
        verAntCli.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbVerDiagClinicoMouseClicked
    /**
     * Método que se ejecuta cuando se hace clic en el componente 'jlbVolver'.
     * Este método abre la ventana de gestión de pacientes y cierra la ventana
     * actual.
     *
     * @param evt El evento.
     */
    private void jlbVerConsuAnterioresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerConsuAnterioresMouseClicked
        VerConsultasAnteriores verHistCli = new VerConsultasAnteriores(control, paciente);
        verHistCli.setVisible(true);
        verHistCli.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbVerConsuAnterioresMouseClicked
    /**
     * Método que se ejecuta cuando se hace clic en el componente 'jlbVolver'.
     * Este método abre la ventana de gestión de pacientes y cierra la ventana
     * actual.
     *
     * @param evt El evento.
     */
    private void jlbVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseClicked
        GestionDePacientes gestP = new GestionDePacientes(control);
        gestP.setVisible(true);
        gestP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbVolverMouseClicked

    private void jlbVerResEstudiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerResEstudiosMouseEntered
        jlbVerResEstudios.setForeground(Color.white);
    }//GEN-LAST:event_jlbVerResEstudiosMouseEntered

    private void jlbVerResEstudiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerResEstudiosMouseExited
        jlbVerResEstudios.setForeground(Color.black);
    }//GEN-LAST:event_jlbVerResEstudiosMouseExited

    private void jlbVerDiagClinicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerDiagClinicoMouseExited
        jlbVerDiagClinico.setForeground(Color.black);
    }//GEN-LAST:event_jlbVerDiagClinicoMouseExited

    private void jlbVerDiagClinicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerDiagClinicoMouseEntered
        jlbVerDiagClinico.setForeground(Color.white);
    }//GEN-LAST:event_jlbVerDiagClinicoMouseEntered

    private void jlbVerConsuAnterioresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerConsuAnterioresMouseEntered
        jlbVerConsuAnteriores.setForeground(Color.white);
    }//GEN-LAST:event_jlbVerConsuAnterioresMouseEntered

    private void jlbVerConsuAnterioresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVerConsuAnterioresMouseExited
        jlbVerConsuAnteriores.setForeground(Color.black);
    }//GEN-LAST:event_jlbVerConsuAnterioresMouseExited

    private void jlbVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseEntered
        jlbVolver.setForeground(Color.white);
    }//GEN-LAST:event_jlbVolverMouseEntered

    private void jlbVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbVolverMouseExited
        jlbVolver.setForeground(Color.black);
    }//GEN-LAST:event_jlbVolverMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datosPActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlbVerConsuAnteriores;
    private javax.swing.JLabel jlbVerDiagClinico;
    private javax.swing.JLabel jlbVerResEstudios;
    private javax.swing.JLabel jlbVolver;
    // End of variables declaration//GEN-END:variables
}
