
package VentanasGUI;

import Model.Box;
import Model.Controladora;
import Model.Paciente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yairc
 */
public class GestionDePacientes extends javax.swing.JFrame {
    Controladora control;
    Paciente pacienteSelecionado;
    String idBox;
    /**
     * Creates new form TomarPaciente
     */
    public GestionDePacientes(Controladora control) {
        initComponents();
        this.control = control;
        btnDatosMedicos.setEnabled(false);
        btnDarDeAlta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTituloPrincipal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBoxAtendidos = new javax.swing.JTable();
        txtTitulo2 = new javax.swing.JLabel();
        btnDarDeAlta = new javax.swing.JButton();
        txbMotivoConsulta = new javax.swing.JTextField();
        btnDatosMedicos = new javax.swing.JButton();
        btnNuevoPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnVolver.setBackground(new java.awt.Color(0, 153, 153));
        btnVolver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        txtTituloPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        txtTituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloPrincipal.setText("Gestion de Pacientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        tablaBoxAtendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaBoxAtendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBoxAtendidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaBoxAtendidos);

        txtTitulo2.setBackground(new java.awt.Color(0, 153, 153));
        txtTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo2.setText("Pacientes en Box");

        btnDarDeAlta.setBackground(new java.awt.Color(0, 204, 153));
        btnDarDeAlta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDarDeAlta.setForeground(new java.awt.Color(0, 0, 0));
        btnDarDeAlta.setText("Dar de alta");
        btnDarDeAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeAltaActionPerformed(evt);
            }
        });

        txbMotivoConsulta.setText("Ingrese diagnostico de la consulta antes ");
        txbMotivoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbMotivoConsultaActionPerformed(evt);
            }
        });

        btnDatosMedicos.setBackground(new java.awt.Color(0, 204, 153));
        btnDatosMedicos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDatosMedicos.setForeground(new java.awt.Color(0, 0, 0));
        btnDatosMedicos.setText("Datos Medicos");
        btnDatosMedicos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDatosMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosMedicosActionPerformed(evt);
            }
        });

        btnNuevoPaciente.setBackground(new java.awt.Color(0, 204, 255));
        btnNuevoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoPaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoPaciente.setText("Nuevo Paciente");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDatosMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txbMotivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addContainerGap(18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTitulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnDatosMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbMotivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este método se activa cuando se hace clic en el botón btnVolver.
     * Crea una nueva instancia de la clase PrincipalMedico, la hace visible y la centra en la pantalla.
     * Cierra la instancia actual.
     * @param evt El evento de acción que ocurrió.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PrincipalMedico princM = new PrincipalMedico(control);
        princM.setVisible(true);
        princM.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

   /**
     * Este método se activa cuando se abre la ventana.
     * Llama al método cargarTabla().
     * @param evt El evento de ventana que ocurrió.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTablaBoxAtendidos();
    }//GEN-LAST:event_formWindowOpened

    private void tablaBoxAtendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBoxAtendidosMouseClicked
        if (tablaBoxAtendidos.getRowCount() > 0) {
            if (tablaBoxAtendidos.getSelectedRow() != -1) {
                int row = tablaBoxAtendidos.getSelectedRow();
                this.idBox = tablaBoxAtendidos.getModel().getValueAt(row, 0).toString();//se obtiene el id del box
                Paciente p = this.control.traerPacienteEnElBox(idBox);
                this.pacienteSelecionado = p;
                btnDarDeAlta.setEnabled(true);
                btnDatosMedicos.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tablaBoxAtendidosMouseClicked

    private void btnDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeAltaActionPerformed
        String diagnostico = this.txbMotivoConsulta.getSelectedText();
        this.control.terminarConsulta(diagnostico, idBox);
    }//GEN-LAST:event_btnDarDeAltaActionPerformed

    private void btnDatosMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosMedicosActionPerformed
        DatosDePaciente datosP = new DatosDePaciente(control,pacienteSelecionado);
        datosP.setVisible(true);
        datosP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDatosMedicosActionPerformed

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        AsignarBox asigBox = new AsignarBox(control);
        asigBox.setVisible(true);
        asigBox.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void txbMotivoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbMotivoConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbMotivoConsultaActionPerformed
    
    /**
     * Este método carga los datos de los Box atendidos por el medico a una tabla.
     */
    private void cargarTablaBoxAtendidos() {
        DefaultTableModel modeloTabla = new DefaultTableModel();        
        String titutlos[] = {"Box","Dni","Apellido"};
        modeloTabla.setColumnIdentifiers(titutlos);
        List<Box> boxes = control.TraerBoxDelMedico();// Obtiene una lista de boxes usando el controlador.
        if (boxes!=null){
            for(Box box : boxes){
                Object[] objeto = {box.getId(),box.getConsulta().getPaciente().getDni(),box.getConsulta().getPaciente().getApellido()};
                modeloTabla.addRow(objeto);// Agrega un objeto a la tabla por cada box del medico.
            }
        }
        tablaBoxAtendidos.setModel(modeloTabla);// Establece el modelo de tabla como modeloTabla.
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarDeAlta;
    private javax.swing.JButton btnDatosMedicos;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaBoxAtendidos;
    private javax.swing.JTextField txbMotivoConsulta;
    private javax.swing.JLabel txtTitulo2;
    private javax.swing.JLabel txtTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
