/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasGUI;

import Model.Controladora;

/**
 *
 * @author Grupo patito
 * Ventana principal para el rol de Gestor del Hospital
 * Contiene las opciones para visualizar datos estadisticos
 * 
 */
public class Gestor extends javax.swing.JFrame {
    Controladora controlG;
    /**
     * Creates new form Gestor
     */
    public Gestor(Controladora control) {
        initComponents();
        this.controlG = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCantPacienteMedico = new javax.swing.JButton();
        btnCantPacienteEdadFecha = new javax.swing.JButton();
        btnPacienteMasConsulta = new javax.swing.JButton();
        btnMedicoMasPaciente = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCantTriage = new javax.swing.JButton();
        btnTriageCambiado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonMiUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCantPacienteMedico.setBackground(new java.awt.Color(0, 204, 204));
        btnCantPacienteMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCantPacienteMedico.setForeground(new java.awt.Color(0, 0, 0));
        btnCantPacienteMedico.setText("Cant. de Pacientes Atendidos Por Médico");
        btnCantPacienteMedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCantPacienteMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantPacienteMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCantPacienteMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 300, 40));

        btnCantPacienteEdadFecha.setBackground(new java.awt.Color(0, 204, 204));
        btnCantPacienteEdadFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCantPacienteEdadFecha.setForeground(new java.awt.Color(0, 0, 0));
        btnCantPacienteEdadFecha.setText("Cant. pacientes atendidos por edad");
        btnCantPacienteEdadFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCantPacienteEdadFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantPacienteEdadFechaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCantPacienteEdadFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 300, 40));

        btnPacienteMasConsulta.setBackground(new java.awt.Color(0, 204, 204));
        btnPacienteMasConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPacienteMasConsulta.setForeground(new java.awt.Color(0, 0, 0));
        btnPacienteMasConsulta.setText("Paciente con más Consultas");
        btnPacienteMasConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPacienteMasConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteMasConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacienteMasConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 300, 40));

        btnMedicoMasPaciente.setBackground(new java.awt.Color(0, 204, 204));
        btnMedicoMasPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMedicoMasPaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnMedicoMasPaciente.setText("Médico con más Pacientes");
        btnMedicoMasPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMedicoMasPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoMasPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedicoMasPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 300, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 140, 40));

        btnCantTriage.setBackground(new java.awt.Color(0, 204, 204));
        btnCantTriage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCantTriage.setForeground(new java.awt.Color(0, 0, 0));
        btnCantTriage.setText("Cant. de Triage y Color");
        btnCantTriage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCantTriage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 300, 40));

        btnTriageCambiado.setBackground(new java.awt.Color(0, 204, 204));
        btnTriageCambiado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTriageCambiado.setForeground(new java.awt.Color(0, 0, 0));
        btnTriageCambiado.setText("Triage Cambiados");
        btnTriageCambiado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTriageCambiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriageCambiadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTriageCambiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 300, 40));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestores Hospitalarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        buttonMiUsuario.setBackground(new java.awt.Color(0, 204, 204));
        buttonMiUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonMiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        buttonMiUsuario.setText("Mi usuario");
        buttonMiUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonMiUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMiUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(buttonMiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Los siguientes botones llevan a las ventanas de carga de datos y visualizacion
     * de cada metodo estadistico en particular
     * @param evt 
     */
    
    /**
     * Cantidad de pacientes atendidos por un medico en particular
     * @param evt 
     */
    private void btnCantPacienteMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantPacienteMedicoActionPerformed
        CantPacientesAtendidosPorMedico cantMedico = new CantPacientesAtendidosPorMedico(this.controlG);
        cantMedico.setVisible(true);
        cantMedico.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCantPacienteMedicoActionPerformed

    /**
     * Cantidad de pacientes atendidos en rango de edad y rango de fechas
     * @param evt 
     */
    private void btnCantPacienteEdadFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantPacienteEdadFechaActionPerformed

        CantPacientesAtendidos cantPaciente = new CantPacientesAtendidos(this.controlG);
        cantPaciente.setVisible(true);
        cantPaciente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCantPacienteEdadFechaActionPerformed

    /**
     * Pacientes que mas consultaron en un rango de fechas
     * @param evt 
     */
    private void btnPacienteMasConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteMasConsultaActionPerformed
        PacientesMasConsultas masConsulta = new PacientesMasConsultas(this.controlG);
        masConsulta.setVisible(true);
        masConsulta.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPacienteMasConsultaActionPerformed

    
    /**
     * Medico que mas pacientes atendio en un rango de fechas
     * @param evt 
     */
    private void btnMedicoMasPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoMasPacienteActionPerformed
        MedicoMasPacientes masPaciente = new MedicoMasPacientes(this.controlG);
        masPaciente.setVisible(true);
        masPaciente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMedicoMasPacienteActionPerformed

    /**
     * Boton que devuelve al Login
     * @param evt 
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        GuiLogin pantallaLogin = new GuiLogin();
        pantallaLogin.setVisible(true);
        pantallaLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * Cantidad de triages cambiados
     * @param evt 
     */
    private void btnTriageCambiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriageCambiadoActionPerformed
        TriageCambiado triagesCambiados = new TriageCambiado(this.controlG);
        triagesCambiados.setVisible(true);
        triagesCambiados.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnTriageCambiadoActionPerformed

    /**
     * La informacion del propio usuario
     * @param evt 
     */
    private void buttonMiUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMiUsuarioMouseClicked
        MiUsuario pantallaUsuario = new MiUsuario(this.controlG);
        pantallaUsuario.setVisible(true);
        pantallaUsuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_buttonMiUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCantPacienteEdadFecha;
    private javax.swing.JButton btnCantPacienteMedico;
    private javax.swing.JButton btnCantTriage;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMedicoMasPaciente;
    private javax.swing.JButton btnPacienteMasConsulta;
    private javax.swing.JButton btnTriageCambiado;
    private javax.swing.JButton buttonMiUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
