/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasGUI;

import Model.FuncionarioGeneral;
import java.util.ArrayList;
import java.util.List;
import java.lang.Object;
/**
 *
 * @author Agus
 */
public class GuiLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public GuiLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar sesion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contraseña:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 210, 147, 34));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Usuario:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 127, 147, 34));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usuario.setCaretColor(new java.awt.Color(0, 0, 0));
        usuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        usuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        usuario.setSelectionColor(new java.awt.Color(204, 204, 204));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel4.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 127, 174, 34));

        contrasenia.setBackground(new java.awt.Color(255, 255, 255));
        contrasenia.setForeground(new java.awt.Color(0, 0, 0));
        contrasenia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contrasenia.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        contrasenia.setSelectionColor(new java.awt.Color(204, 204, 204));
        contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaActionPerformed(evt);
            }
        });
        jPanel4.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 174, 34));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Iniciar sesion");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setInheritsPopupMenu(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 282, 174, 37));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
<<<<<<< HEAD
        String usern = usuario.getText();
        String passw = String.valueOf(contraseña.getPassword());
        Controladora verif = new Controladora();
        boolean resultado = verif.validar(usern, passw);
        if (resultado) {
            String rolEncontrado;
            List<FuncionarioGeneral> listFunGral = verif.traerFuncionariosEnGeneral();
            if (!listFunGral.isEmpty()) {
                for (FuncionarioGeneral buscar : listFunGral) {
                    if (usern == buscar.getNomUsuario()) {
                        rolEncontrado = buscar.getRol().getNombre();
                        break;
                    }
                }
            }
        }
            
=======

//        String usern = usuario.getText();
//        String passw = String.valueOf(contraseña.getPassword());
//        Controladora verif = new Controladora();
//        boolean resultado = verif.validar(usern, passw);
//        if (resultado) {
//            String rolEncontrado;
//            List<FuncionarioGeneral> listFunGral = verif.traerFuncionariosEnGeneral();
//            if (!listFunGral.isEmpty()) {
//                for (FuncionarioGeneral buscar : listFunGral) {
//                    if (usern == buscar.getNomUsuario()) {
//                        rolEncontrado = buscar.getRol().getNombre();
//                        break;
//                    }
//                }
//            }
//            
>>>>>>> f1b2a889c99d5a30cb19cdc03a672a061b0e52e6
//            switch (rolEncontrado) {
//                case "Gestor":
//                    
//                    break;
//                
//                case "Recepcionista":
//                    break;
//                
//                case "Medico":
//                    break;
//                
//                case "Licenciando en Enfermeria":
//                    break;
//                
//                case "Administrador de Sistema":
//                    break;
//                
//                default:
//                    break;
//                }
//            }
            
         
        
//        String usern = usuario.getText();
//        String passw = String.valueOf(contrasenia.getPassword());
//        Controladora verif = new Controladora();
//        ArrayList<Object> resultado = verif.validar(usern, passw);
//        String idUser = "";
//        String rolEncontrado = "";
//        if ((Boolean) resultado.get(0)) {
//            idUser = (String) resultado.get(1);
//            rolEncontrado = (String) resultado.get(2);
//        }
//            
//        switch (rolEncontrado) {
//            case "Gestor":
//                //GestionHospital pantalla1 = new GestionHospital();
//                pantalla1.setVisible(true);
//                pantalla1.setLocationRelativeTo(null);
//                this.dispose();
//                break;
//                
//            case "Recepcionista":
//                //Recepcion pantalla2 = new Recepcion();
//                pantalla2.setVisible(true);
//                pantalla2.setLocationRelativeTo(null);
//                this.dispose();
//                break;
//                
//            case "Medico":
//                PpalMedico pantalla3 = new PpalMedico();
//                pantalla3.setVisible(true);
//                pantalla3.setLocationRelativeTo(null);
//                this.dispose();
//                break;
//                
//            case "Licenciando en Enfermeria":
//                PpalMedico pantalla4 = new PpalMedico();
//                pantalla4.setVisible(true);
//                pantalla4.setLocationRelativeTo(null);
//                this.dispose();
//                break;
//                
//            case "Administrador de Sistema":
//                Administrador pantalla5 = new Administrador();
//                pantalla5.setVisible(true);
//                pantalla5.setLocationRelativeTo(null);
//                this.dispose();
//                break;
//                
//            default:
//                break;
//                }
    }//GEN-LAST:event_jButton1MouseClicked

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
