/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasGUI;
import Model.Controladora;
/**
 *
 * @author yairc
 */
public class PrincipalMedico extends javax.swing.JFrame {
    Controladora control;
    /**
     * Creates new form Medico
     */
    public PrincipalMedico(Controladora control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtHacerTriage = new javax.swing.JButton();
        txtTomarPaciente = new javax.swing.JButton();
        txtDatosDePaciente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtHacerTriage.setBackground(new java.awt.Color(0, 204, 255));
        txtHacerTriage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHacerTriage.setForeground(new java.awt.Color(0, 0, 0));
        txtHacerTriage.setText("Hacer Triage");
        txtHacerTriage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHacerTriageActionPerformed(evt);
            }
        });

        txtTomarPaciente.setBackground(new java.awt.Color(0, 204, 255));
        txtTomarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTomarPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtTomarPaciente.setText("Tomar Paciente");
        txtTomarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTomarPacienteActionPerformed(evt);
            }
        });

        txtDatosDePaciente.setBackground(new java.awt.Color(0, 204, 255));
        txtDatosDePaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDatosDePaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtDatosDePaciente.setText("HistoriaClinica");
        txtDatosDePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosDePacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHacerTriage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTomarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(txtDatosDePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTomarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtDatosDePaciente)
                .addGap(18, 18, 18)
                .addComponent(txtHacerTriage)
                .addGap(114, 114, 114))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 260, 260));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label1.setText("Panel Medico ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHacerTriageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHacerTriageActionPerformed
        HacerTriage hacerT = new HacerTriage();
        hacerT.setVisible(true);
        hacerT.setLocationRelativeTo(null);
    }//GEN-LAST:event_txtHacerTriageActionPerformed

    private void txtTomarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTomarPacienteActionPerformed
        TomarPaciente tomarP = new TomarPaciente(control);
        tomarP.setVisible(true);
        tomarP.setLocationRelativeTo(null);
    }//GEN-LAST:event_txtTomarPacienteActionPerformed

    private void txtDatosDePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosDePacienteActionPerformed
        HistoriaClinica verDatoP = new HistoriaClinica(control);
        verDatoP.setVisible(true);
        verDatoP.setLocationRelativeTo(null);
    }//GEN-LAST:event_txtDatosDePacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private javax.swing.JButton txtDatosDePaciente;
    private javax.swing.JButton txtHacerTriage;
    private javax.swing.JButton txtTomarPaciente;
    // End of variables declaration//GEN-END:variables
}
