package VentanasGUI;

import Model.Controladora;
import Model.Rol;
import java.util.List;

/**
 * Esta clase representa una ventana de la interfaz gráfica de usuario que
 * permite seleccionar entre Gestionar Pacientes y Hacer Triage segun el rol del
 * mismo.
 *
 * @author yairc
 */
public class PrincipalMedico extends javax.swing.JFrame {

    Controladora control;

    /**
     * Constructor de PrincipalMedico
     *
     * @param control
     */
    public PrincipalMedico(Controladora control) {
        initComponents();
        this.control = control;
        identificarRol();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHacerTriage = new javax.swing.JButton();
        btnGestioDePaciente = new javax.swing.JButton();
        btnMiUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnHacerTriage.setBackground(new java.awt.Color(0, 204, 255));
        btnHacerTriage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHacerTriage.setForeground(new java.awt.Color(0, 0, 0));
        btnHacerTriage.setText("Hacer Triage");
        btnHacerTriage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerTriageActionPerformed(evt);
            }
        });

        btnGestioDePaciente.setBackground(new java.awt.Color(0, 204, 255));
        btnGestioDePaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGestioDePaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnGestioDePaciente.setText("Gestion de Pacientes");
        btnGestioDePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioDePacienteActionPerformed(evt);
            }
        });

        btnMiUsuario.setBackground(new java.awt.Color(0, 204, 255));
        btnMiUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btnMiUsuario.setText("Mi Usuario");
        btnMiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestioDePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnHacerTriage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnMiUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnHacerTriage)
                .addGap(18, 18, 18)
                .addComponent(btnGestioDePaciente)
                .addGap(18, 18, 18)
                .addComponent(btnMiUsuario)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 160));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label2.setText("Gestion Medica");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este método se activa cuando se realiza una acción en el botón
     * btnHacerTriage. Crea una nueva instancia de la clase HacerTriage, la hace
     * visible y la centra en la pantalla.
     *
     * @param evt El evento de acción que ocurrió.
     */
    private void btnHacerTriageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerTriageActionPerformed
        // Creamos una nueva instancia de la ventana EsperaTriage
        EsperaTriage hacerT = new EsperaTriage(control);
        // Hacemos visible la ventana
        hacerT.setVisible(true);
        // Centramos la ventana en la pantalla
        hacerT.setLocationRelativeTo(null);
        // Cerramos la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnHacerTriageActionPerformed
    /**
     * Este método se activa cuando se realiza una acción en el botón
     * btnGestionDePaciente. Crea una nueva instancia de la clase
     * GestionDePaciente, la hace visible y la centra en la pantalla.
     *
     * @param evt El evento de acción que ocurrió.
     */
    private void btnGestioDePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioDePacienteActionPerformed
        // Creamos una nueva instancia de la ventana GestionDePacientes
        GestionDePacientes tomarP = new GestionDePacientes(control);
        // Hacemos visible la ventana
        tomarP.setVisible(true);
        // Centramos la ventana en la pantalla
        tomarP.setLocationRelativeTo(null);
        // Cerramos la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnGestioDePacienteActionPerformed
    /**
     * Este método se activa cuando se realiza una acción en el botón btnMiUsuario.
     * Crea una nueva instancia de la clase MiUsuario, la hace visible y la
     * centra en la pantalla.
     *
     * @param evt El evento de acción que ocurrió.
     */
    private void btnMiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiUsuarioActionPerformed
        // Creamos una nueva instancia de la ventana MiUsuario
        MiUsuario miUsu = new MiUsuario(control);
        // Hacemos visible la ventana
        miUsu.setVisible(true);
        // Centramos la ventana en la pantalla
        miUsu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMiUsuarioActionPerformed

    /**
     * Este método identifica el rol del usuario y habilita los botones
     * correspondientes en la interfaz. Recorre la lista de roles del usuario y
     * habilita los botones de 'Gestión de Paciente' y 'Hacer Triage' según
     * corresponda.
     */
    private void identificarRol() {
        btnGestioDePaciente.setEnabled(false);
        btnHacerTriage.setEnabled(false);
        try {
            // Obtenemos la lista de roles del usuario
            List<Rol> roles = this.control.getUsu().getRol();

            // Recorremos la lista de roles
            for (Rol rol : roles) {
                // Obtenemos el nombre del rol
                String nombreRol = rol.getNombre();

                // Según el nombre del rol, habilitamos los botones correspondientes
                switch (nombreRol) {
                    case "Medico - Atencion" -> {
                        // Si el rol es 'Medico - Atencion', habilitamos el botón 'GestioDePaciente' y deshabilitamos el botón 'HacerTriage'
                        btnGestioDePaciente.setEnabled(true);
                        btnHacerTriage.setEnabled(false);
                    }
                    case "Medico - Triage" -> {
                        // Si el rol es 'Medico - Triage', deshabilitamos el botón 'GestioDePaciente' y habilitamos el botón 'HacerTriage'
                        btnGestioDePaciente.setEnabled(false);
                        btnHacerTriage.setEnabled(true);
                    }
                    default -> {
                        // Si el rol es cualquier otro, habilitamos ambos botones
                        btnGestioDePaciente.setEnabled(true);
                        btnHacerTriage.setEnabled(true);
                    }
                }
            }
        } catch (Exception e) {
            // Si ocurre un error, mostramos un mensaje de error
            System.out.println("Error: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestioDePaciente;
    private javax.swing.JButton btnHacerTriage;
    private javax.swing.JButton btnMiUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
