
package VentanasGUI;

import Model.Box;
import Model.Consulta;
import Model.Controladora;
import Model.Medico;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yairc
 */
public class TomarPaciente extends javax.swing.JFrame {
    Controladora control;
    String boxSeleccionadoId;
    /**
     * Creates new form TomarPaciente
     */
    public TomarPaciente(Controladora control) {
        initComponents();
        this.control = control;
        this.boxSeleccionadoId = null;
        btnElegirP.setEnabled(false);
        btnDarDeAlta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPEnEspera = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnElegirP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTituloPrincipal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBoxAtendidos = new javax.swing.JTable();
        txtTitulo1 = new javax.swing.JLabel();
        txtTitulo2 = new javax.swing.JLabel();
        btnDarDeAlta = new javax.swing.JButton();
        txfMotivoConsulta = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBox = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaPEnEspera.setBackground(new java.awt.Color(255, 255, 255));
        tablaPEnEspera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaPEnEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPEnEspera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPEnEsperaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPEnEspera);

        btnVolver.setBackground(new java.awt.Color(0, 153, 153));
        btnVolver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnElegirP.setBackground(new java.awt.Color(0, 204, 153));
        btnElegirP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnElegirP.setForeground(new java.awt.Color(0, 0, 0));
        btnElegirP.setText("Asignar Box");
        btnElegirP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnElegirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirPActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        txtTituloPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        txtTituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloPrincipal.setText("Gestion de Pacientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(txtTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tablaBoxAtendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaBoxAtendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBoxAtendidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaBoxAtendidos);

        txtTitulo1.setBackground(new java.awt.Color(0, 153, 153));
        txtTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo1.setText("Pacientes en Espera");

        txtTitulo2.setBackground(new java.awt.Color(0, 153, 153));
        txtTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo2.setText("Pacientes en Box");

        btnDarDeAlta.setBackground(new java.awt.Color(0, 204, 153));
        btnDarDeAlta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDarDeAlta.setForeground(new java.awt.Color(0, 0, 0));
        btnDarDeAlta.setText("Dar de alta");
        btnDarDeAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeAltaActionPerformed(evt);
            }
        });

        txfMotivoConsulta.setText("Ingrese diagnostico de la consulta");

        tablaBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaBox);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtTitulo1)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txfMotivoConsulta))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(txtTitulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegirP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegirP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMotivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este método se activa cuando se hace clic en el botón btnVolver.
     * Crea una nueva instancia de la clase PrincipalMedico, la hace visible y la centra en la pantalla.
     * Cierra la instancia actual.
     * @param evt El evento de acción que ocurrió.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PrincipalMedico princM = new PrincipalMedico(control);
        princM.setVisible(true);
        princM.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    /**
     * Este método se activa cuando se hace clic en el botón btnElegirP.
     * Crea una nueva instancia de la clase AsignarBox, la hace visible y la centra en la pantalla.
     * Cierra la instancia actual.
     * @param evt El evento de acción que ocurrió.
     */
    private void btnElegirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirPActionPerformed
        AsignarBox asigBox = new AsignarBox(control);
        asigBox.setVisible(true);
        asigBox.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnElegirPActionPerformed
    /**
     * Este método se activa cuando se abre la ventana.
     * Llama al método cargarTabla().
     * @param evt El evento de ventana que ocurrió.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
        cargarTablaBoxAtendidos();
    }//GEN-LAST:event_formWindowOpened

    private void tablaPEnEsperaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPEnEsperaMouseClicked
        if (tablaPEnEspera.getRowCount() > 0) {
            if (tablaPEnEspera.getSelectedRow() != -1) {
                int row = tablaPEnEspera.getSelectedRow();
                String dni = tablaPEnEspera.getModel().getValueAt(row, 0).toString();
                this.dniP = dni;
                btnElegirP.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tablaPEnEsperaMouseClicked

    private void tablaBoxAtendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBoxAtendidosMouseClicked
        if (tablaPEnEspera.getRowCount() > 0) {
            if (tablaPEnEspera.getSelectedRow() != -1) {
                int row = tablaPEnEspera.getSelectedRow();
                String idBox = tablaPEnEspera.getModel().getValueAt(row, 0).toString();//se obtiene el id del box
                this.boxSeleccionadoId = idBox;
                btnDarDeAlta.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tablaBoxAtendidosMouseClicked

    private void btnDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeAltaActionPerformed
        
        control.terminarConsulta(boxSeleccionadoId);
    }//GEN-LAST:event_btnDarDeAltaActionPerformed
    /**
     * Este método carga los datos de los pacientes triageados en una tabla.
     */
    private void cargarTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel();        
        String titutlos[] = {"Dni","Nombre","Color Triage","Motivo Consulta"};
        modeloTabla.setColumnIdentifiers(titutlos);        
        List<Consulta> listP = control.TraerPacientesTriageados();// Obtiene una lista de pacientes triageados utilizando el controlador.
        if (listP!=null){
            for(Consulta consu : listP){
                Object[] objeto = {consu.getPaciente().getDni(), consu.getPaciente().getNombre()+""+consu.getPaciente().getApellido(), consu.getTriage().getColorFinal(), consu.getMotivo()};
                modeloTabla.addRow(objeto);// Agrega un objeto a la tabla por cada paciente triageado en listP.
            }
        }
        tablaPEnEspera.setModel(modeloTabla);// Establece el modelo de tabla como modeloTabla.
    }
    /**
     * Este método carga los datos de los Box atendidos por el medico a una tabla.
     */
    private void cargarTablaBoxAtendidos() {
        DefaultTableModel modeloTabla = new DefaultTableModel();        
        String titutlos[] = {"Box","Dni","Apellido"};
        modeloTabla.setColumnIdentifiers(titutlos);
        List<Box> boxes = control.TraerBoxDelMedico();// Obtiene una lista de boxes usando el controlador.
        if (boxes!=null){
            for(Box box : boxes){
                Object[] objeto = {box.getId(),box.getPacienteActual().getDni(),box.getPacienteActual().getApellido()};
                modeloTabla.addRow(objeto);// Agrega un objeto a la tabla por cada box del medico.
            }
        }
        tablaBoxAtendidos.setModel(modeloTabla);// Establece el modelo de tabla como modeloTabla.
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarDeAlta;
    private javax.swing.JButton btnElegirP;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaBox;
    private javax.swing.JTable tablaBoxAtendidos;
    private javax.swing.JTable tablaPEnEspera;
    private javax.swing.JTextField txfMotivoConsulta;
    private javax.swing.JLabel txtTitulo1;
    private javax.swing.JLabel txtTitulo2;
    private javax.swing.JLabel txtTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
